version: "3.9"
services:
  api:
    container_name: online_shop_api
    build:
      context: ./../
      dockerfile: ./ShopOnline.Api/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  web:
    container_name: online_shop_web
    build:
      context: ./../
      dockerfile: ./ShopOnline.Web/Dockerfile
    ports:
      - '8080:80'